[project]
name = "sae_auto_interp"
version = "0.1.0"
description = "Automated Interpretability"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets",
    "nnsight",
    "orjson",
    "sae",
    "safetensors",
    "simple_parsing",
    "torchtyping>=0.1.5",
    "fire",
    "blobfile",
    "transformer_lens",
    "bitsandbytes",
    "flask",
    "vllm",
    "aiofiles",
    "sentence-transformers",
    "dspy>=2.6.0rc5",
    "ipython>=8.31.0",
    "zstandard>=0.23.0",
    "numba>=0.60.0",
]
dev-dependencies = [
    "pyright",
    "ruff",
]

[sources.sae]
git = "https://github.com/EleutherAI/sae"

[tool.ruff]
# TODO: Clean up or remove experiments folder.
exclude = ["experiments", "**/prompts/*", "**/prompts.py","**/simulator.py"]
# Avoid automatically removing unused imports in __init__.py files.
# Such imports will be flagged with a dedicated message suggesting
# that the import is either added to the module's __all__ symbol
ignore-init-module-imports = true
# Ignore F821 (undefined name) errors, as they are common in type annotations.
ignore = ["F722", "F821"]
# Same as Black.
line-length = 88
# Enable pycodestyle (`E`), Pyflakes (`F`), and isort (`I`) codes
# See https://beta.ruff.rs/docs/rules/ for more possible rules
select = ["E", "F", "I"]

[tool.uv.sources]
sae = { git = "https://github.com/EleutherAI/sae" }

[dependency-groups]
dev = [
    "ruff>=0.8.5",
    "pyright",
]
